### PR TITLE
Add a padding between the song title and the favorite indicator

### PR DESCRIPTION
**Pull request by Abestanis**
| Before    | Before |
|-----------|-------|
| **After** | After |

### CODE REVIEW

**Comment by nt4f04uNd** [comment]
Ok, this was an oversight on my part, but why is this only for song tile though? Can you just make the padding inside FavoriteIndicator symmetric?

**Comment by Abestanis** [comment]
> Can you just make the padding inside FavoriteIndicator symmetric?

Done.

**Comment by Abestanis** [comment]
I'm also regenerating the goldens.

**Comment by Abestanis** [comment]
> I'm also regenerating the goldens.

Ok, looks like none of these differences were actually related to the changes in this PR, but I still think it would be good to update them so we get a good baseline again.

**Comment by Abestanis** [comment]
> It's better to regenerate them to baseline where this is really needed to not clutter up the diff with lots of identical images.

Ok, we'll update them in #51.

**Pull request merged**
