### PR TITLE
Support Material You monochrome app icon

### PR DESCRIPTION
**Pull request by nt4f04uNd**
Fixes https://github.com/nt4f04uNd/sweyer/issues/112

Снимок экрана 2023-05-06 в 23 12 58

### CODE REVIEW

**Comment by Abestanis** [comment]
I think since this is an API 31+ feature, we should use a vector image: 
[ic_launcher_monochrome.zip](https://github.com/nt4f04uNd/sweyer/files/11416028/ic_launcher_monochrome.zip)

But what do you think about keeping the shadow? 
[ic_launcher_monochrome.zip](https://github.com/nt4f04uNd/sweyer/files/11416029/ic_launcher_monochrome.zip)
| Without shadow | With shadow |
| ------------------ | -------------- |
| Icon before | Icon with shadow |

**Comment by nt4f04uNd** [comment]
Incredible, thank you! 🔥

Sure, with the shadow it's better.

I tried making it with a shadow, but failed because I used the raw SVG asset.
I now see that you already made such an asset for the splash screen in the past.

**Review by Abestanis — APPROVED** [review]
Nice, looks awesome!

Do you want me to merge the pull requests where you assign me as a reviewer?

**Comment by nt4f04uNd** [comment]
> Do you want me to merge the pull requests where you assign me as a reviewer?

Also, I will assign you to all my PRs, if you don't mind.
I enabled master branch protection rule that prevents merging without at least 1 approval.

**Comment by Abestanis** [comment]
Yes, perfect. 👍 It's always better to have a second pair of eyes read the code before merging in my opinion.

**Pull request merged**
